name: Check Geofabrik Latest

on:
  workflow_dispatch: # manual run
  #schedule:
  #  - cron: '0 2 * * 1' # weekly run, Monday 02:00

jobs:
  check-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write  # required to trigger another workflow via repository-dispatch
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get current DATA_VERSION
        id: get_current
        run: |
          if [ -f data/geojson/DATA_VERSION.txt ]; then
            CURRENT=$(cat data/geojson/DATA_VERSION.txt)
          else
            CURRENT=0
          fi
          echo "current=$CURRENT" >> $GITHUB_OUTPUT

      - name: Get latest Geofabrik date
        id: get_latest
        run: |
          DATE=$(python scripts/geofabrik_date.py)
          echo "latest=$DATE" >> $GITHUB_OUTPUT

      - name: Compare dates
        id: compare
        run: |
          if [ "${{ steps.get_latest.outputs.latest }}" -gt "${{ steps.get_current.outputs.current }}" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger update-data if needed
        if: steps.compare.outputs.update_needed == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_FOR_DISPATCH }}
          repository: ${{ github.repository }}
          event-type: update-data
